version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: api
    restart: always
    ports:
      - 5229:5229
    cap_add:
      - "SYS_TIME"
    user: root
    environment:
      - ASPNETCORE_URLS=http://+:5229
#      - ASPNETCORE_URLS=https://+:5228;http://+:5229
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
#    volumes:
#      - ~/.aspnet/https:/https:ro
    # command: docker container exec date-api-1 date -s "2023-07-15 15:15"

    # dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.pfx -p $CREDENTIAL_PLACEHOLDER$
    # dotnet dev-certs https --trust
    # In the preceding commands, replace $CREDENTIAL_PLACEHOLDER$ with a password.
    # https://learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-6.0

