version: '3.8'

services:

  api:
    image: date-api-dev:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    ports:
      - 5229-5231:5229
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5229
    volumes:
      - ~/.aspnet/https:/https:ro
    deploy:
      mode: replicated
      replicas: 3