version: '3.8'

services:

  api:
    image: 127.0.0.1:5000/date-api-dev:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    ports:
      - 5229:5229
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5229
    volumes:
      - ~/.aspnet/https:/https:ro
    deploy:
      mode: replicated
      replicas: 3

  # lb:
  #   build: caddy
  #   ports:
  #     - 80:80