version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: api
    restart: always
    ports:
      - 5229:5229
      # - 5228:5228
    # cap_add:
    #   - "SYS_TIME"
    user: root
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5229
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    # command: docker container exec date-api-1 date -s "2023-07-15 15:15"
